use std::{collections::BTreeSet, env, fs, path::PathBuf};

use quote::ToTokens;
use syn::{
  Fields, GenericArgument, Item, ItemEnum, ItemStruct, PathArguments, Type, Visibility,
};

const GENERATED_HARDWARE_MODELS: &[&str] = &[
  "MemoryInfo",
  "GraphicInfo",
  "GpuMemoryUsage",
  "GpuUsageResult",
  "NameValue",
  "StorageInfo",
  "StorageHealthStatus",
  "StorageWarningLevel",
  "StorageHealthRecord",
  "LiveStorageHealth",
  "NetworkInfo",
  "ProcessInfo",
  "MotherboardInfo",
  "SuperIoChipIdDiagnostics",
  "PawnIoRuntimeDiagnostics",
  "SuperIoChipIdSlotProbe",
  "SuperIoChipIdAttempt",
  "SuperIoVendor",
  "SysInfo",
  "CpuInfo",
];

fn main() {
  generate_hardware_models();
  tauri_build::build()
}

fn generate_hardware_models() {
  let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
  let source_path = manifest_dir.join("../core/src/models/hardware.rs");
  println!("cargo:rerun-if-changed={}", source_path.display());

  let source = fs::read_to_string(&source_path)
    .unwrap_or_else(|error| panic!("failed to read {}: {error}", source_path.display()));
  let syntax = syn::parse_file(&source)
    .unwrap_or_else(|error| panic!("failed to parse {}: {error}", source_path.display()));
  let items = collect_model_items(&syntax);
  let generated_names = items.iter().map(item_name).collect::<BTreeSet<_>>();
  validate_generated_models_found(&generated_names);

  let mut output = String::from(
    "// @generated by src-tauri/build.rs from core/src/models/hardware.rs\n\
     // Do not edit this file directly.\n\n",
  );

  for item in &items {
    match item {
      Item::Struct(item) => output.push_str(&generate_struct(item)),
      Item::Enum(item) => output.push_str(&generate_enum(item)),
      _ => unreachable!("collect_model_items only returns structs and enums"),
    }
  }

  for item in &items {
    match item {
      Item::Struct(item) => {
        output.push_str(&generate_struct_from_impl(item, &generated_names));
      }
      Item::Enum(item) => output.push_str(&generate_enum_from_impl(item)),
      _ => unreachable!("collect_model_items only returns structs and enums"),
    }
  }

  let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
  fs::write(out_dir.join("hardware_models.rs"), output)
    .expect("failed to write generated hardware models");
}

fn collect_model_items(syntax: &syn::File) -> Vec<&Item> {
  syntax
    .items
    .iter()
    .filter(|item| match item {
      Item::Struct(item) => is_public(&item.vis) && should_generate(&item.ident),
      Item::Enum(item) => is_public(&item.vis) && should_generate(&item.ident),
      _ => false,
    })
    .collect()
}

fn should_generate(ident: &syn::Ident) -> bool {
  let ident = ident.to_string();
  GENERATED_HARDWARE_MODELS
    .iter()
    .any(|model| *model == ident)
}

fn validate_generated_models_found(found: &BTreeSet<String>) {
  let missing = GENERATED_HARDWARE_MODELS
    .iter()
    .filter(|model| !found.contains(**model))
    .copied()
    .collect::<Vec<_>>();

  if !missing.is_empty() {
    panic!(
      "missing generated hardware model sources: {}",
      missing.join(", ")
    );
  }
}

fn is_public(vis: &Visibility) -> bool {
  matches!(vis, Visibility::Public(_))
}

fn item_name(item: &&Item) -> String {
  match item {
    Item::Struct(item) => item.ident.to_string(),
    Item::Enum(item) => item.ident.to_string(),
    _ => unreachable!("collect_model_items only returns structs and enums"),
  }
}

fn generate_struct(item: &ItemStruct) -> String {
  let name = item.ident.to_string();
  let mut output = format!(
    "#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, specta::Type)]\n\
     #[serde(rename_all = \"camelCase\")]\n\
     pub struct {name} {{\n"
  );

  let Fields::Named(fields) = &item.fields else {
    panic!("{name} must use named fields for hardware DTO generation");
  };

  for field in &fields.named {
    let field_name = field
      .ident
      .as_ref()
      .expect("named field must have an ident")
      .to_string();
    output.push_str(&field_attrs(&name, &field_name));
    output.push_str(&format!(
      "  pub {field_name}: {},\n",
      app_type_string(&field.ty)
    ));
  }

  output.push_str("}\n\n");
  output
}

fn generate_enum(item: &ItemEnum) -> String {
  let name = item.ident.to_string();
  let mut output = format!(
    "#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, specta::Type)]\n\
     #[serde(rename_all = \"camelCase\")]\n\
     pub enum {name} {{\n"
  );

  for variant in &item.variants {
    if !matches!(variant.fields, Fields::Unit) {
      panic!("{name}::{} must be a unit variant", variant.ident);
    }
    output.push_str(&format!("  {},\n", variant.ident));
  }

  output.push_str("}\n\n");
  output
}

fn field_attrs(struct_name: &str, field_name: &str) -> String {
  if struct_name == "ProcessInfo" && matches!(field_name, "cpu_usage" | "memory_usage") {
    return "  #[serde(serialize_with = \"super::serialize_usage\")]\n  #[specta(type = String)]\n"
      .to_string();
  }

  String::new()
}

fn generate_struct_from_impl(
  item: &ItemStruct,
  generated_names: &BTreeSet<String>,
) -> String {
  let name = item.ident.to_string();
  let core_type = core_type_path(&name);
  let mut output = format!(
    "impl From<{core_type}> for {name} {{\n  fn from(src: {core_type}) -> Self {{\n    Self {{\n"
  );

  let Fields::Named(fields) = &item.fields else {
    panic!("{name} must use named fields for hardware DTO generation");
  };

  for field in &fields.named {
    let field_name = field
      .ident
      .as_ref()
      .expect("named field must have an ident")
      .to_string();
    let access = format!("src.{field_name}");
    output.push_str(&format!(
      "      {field_name}: {},\n",
      conversion_expr(&field.ty, &access, generated_names)
    ));
  }

  output.push_str("    }\n  }\n}\n\n");
  output
}

fn generate_enum_from_impl(item: &ItemEnum) -> String {
  let name = item.ident.to_string();
  let core_type = core_type_path(&name);
  let mut output = format!(
    "impl From<{core_type}> for {name} {{\n  fn from(src: {core_type}) -> Self {{\n    match src {{\n"
  );

  for variant in &item.variants {
    let variant_name = variant.ident.to_string();
    output.push_str(&format!(
      "      {core_type}::{variant_name} => Self::{variant_name},\n"
    ));
  }

  output.push_str("    }\n  }\n}\n\n");
  output
}

fn core_type_path(name: &str) -> String {
  format!("hardviz_core::models::hardware::{name}")
}

fn app_type_string(ty: &Type) -> String {
  if let Some((outer, inner)) = single_type_arg(ty) {
    return format!("{outer}<{}>", app_type_string(inner));
  }

  if let Some(ident) = simple_type_ident(ty) {
    return match ident.as_str() {
      "DiskKind" => "super::DiskKind".to_string(),
      "SizeUnit" => "super::SizeUnit".to_string(),
      _ => ident,
    };
  }

  ty.to_token_stream().to_string()
}

fn conversion_expr(
  ty: &Type,
  access: &str,
  generated_names: &BTreeSet<String>,
) -> String {
  if let Some((outer, inner)) = single_type_arg(ty) {
    return match outer.as_str() {
      "Option" => option_conversion_expr(inner, access, generated_names),
      "Vec" => vec_conversion_expr(inner, access, generated_names),
      _ => access.to_string(),
    };
  }

  if needs_conversion(ty, generated_names) {
    format!("{access}.into()")
  } else {
    access.to_string()
  }
}

fn option_conversion_expr(
  inner: &Type,
  access: &str,
  generated_names: &BTreeSet<String>,
) -> String {
  if let Some((outer, nested)) = single_type_arg(inner)
    && outer == "Vec"
    && needs_conversion(nested, generated_names)
  {
    return format!("{access}.map(|items| items.into_iter().map(Into::into).collect())");
  }

  if needs_conversion(inner, generated_names) {
    format!("{access}.map(Into::into)")
  } else {
    access.to_string()
  }
}

fn vec_conversion_expr(
  inner: &Type,
  access: &str,
  generated_names: &BTreeSet<String>,
) -> String {
  if needs_conversion(inner, generated_names) {
    format!("{access}.into_iter().map(Into::into).collect()")
  } else {
    access.to_string()
  }
}

fn needs_conversion(ty: &Type, generated_names: &BTreeSet<String>) -> bool {
  if let Some((outer, inner)) = single_type_arg(ty) {
    return match outer.as_str() {
      "Option" | "Vec" => needs_conversion(inner, generated_names),
      _ => false,
    };
  }

  simple_type_ident(ty).is_some_and(|ident| {
    matches!(ident.as_str(), "DiskKind" | "SizeUnit") || generated_names.contains(&ident)
  })
}

fn single_type_arg(ty: &Type) -> Option<(String, &Type)> {
  let Type::Path(type_path) = ty else {
    return None;
  };
  if type_path.qself.is_some() || type_path.path.segments.len() != 1 {
    return None;
  }

  let segment = type_path.path.segments.first()?;
  let PathArguments::AngleBracketed(args) = &segment.arguments else {
    return None;
  };
  let inner = args.args.iter().find_map(|arg| match arg {
    GenericArgument::Type(ty) => Some(ty),
    _ => None,
  })?;
  Some((segment.ident.to_string(), inner))
}

fn simple_type_ident(ty: &Type) -> Option<String> {
  let Type::Path(type_path) = ty else {
    return None;
  };
  if type_path.qself.is_some() || type_path.path.segments.len() != 1 {
    return None;
  }
  let segment = type_path.path.segments.first()?;
  if !matches!(segment.arguments, PathArguments::None) {
    return None;
  }
  Some(segment.ident.to_string())
}
