name: "Setup Rust Environment"
description: "Setup Rust toolchain with caching and components"
inputs:
  components:
    description: "Additional components to install"
    required: false
    default: "rustfmt clippy"

runs:
  using: "composite"
  steps:
    - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
      with:
        workspaces: "src-tauri -> target"

    - name: Install Rust components
      if: inputs.components != ''
      run: rustup component add ${{ inputs.components }}
      shell: bash
