changelog:
  exclude:
    labels: ["release:skip", ignore-for-release, no-release-notes]
    authors:
      - dependabot[bot]
      - dependabot
      - hardwarevisualizerappmanager[bot]

  categories:
    - title: Added
      labels: ["change:feature", feature, enhancement]
    - title: Fixed
      labels: ["change:fix", bug]
    - title: Maintenance
      labels:
        [
          "change:ci",
          "change:docs",
          "change:deps",
          "change:config",
          "change:test",
          "change:refactor",
          ci,
          docs,
          documentation,
          dependencies,
          configuration,
          refactor,
        ]
    - title: Other Changes
      labels: ["*"]
