// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	// Fetch available update metadata
	fetchUpdate: () => typedError<{
	version: string,
	currentVersion: string,
	notes: string | null,
	pubDate: string | null,
} | null, UpdaterError>(__TAURI_INVOKE("fetch_update")),
	// Install the pending update
	installUpdate: (onEvent: Channel<DownloadEvent>) => typedError<null, UpdaterError>(__TAURI_INVOKE("install_update", { onEvent })),
	// ## Get process list
	getProcessList: () => __TAURI_INVOKE<ProcessInfo_Serialize[]>("get_process_list"),
	/**
	 *  ## Get CPU usage (%)
	 * 
	 *  - param state: shared `HistoryStore` from the Core collector.
	 *  - return: `i32` overall CPU usage (%)
	 */
	getCpuUsage: () => __TAURI_INVOKE<number>("get_cpu_usage"),
	// ## Get system information
	getHardwareInfo: () => typedError<SysInfo, string>(__TAURI_INVOKE("get_hardware_info")),
	/**
	 *  ## Get detailed memory information
	 * 
	 *  - return: `models::hardware::MemoryInfo` Detailed memory information
	 */
	getMemoryInfoDetail: () => typedError<MemoryInfo, string>(__TAURI_INVOKE("get_memory_info_detail")),
	/**
	 *  ## Get memory usage (%)
	 * 
	 *  - param state: shared `HistoryStore`.
	 *  - return: `i32` Memory usage (%)
	 */
	getMemoryUsage: () => __TAURI_INVOKE<number>("get_memory_usage"),
	/**
	 *  ## Get GPU usage (%)
	 * 
	 *  Returns the GPU usage percentage together with the data-source
	 *  identifier (e.g. "NVAPI", "ADL", "PDH", "DRM (AMD)", "IOKit").
	 */
	getGpuUsage: () => typedError<GpuUsageResult, string>(__TAURI_INVOKE("get_gpu_usage")),
	getProcessorsUsage: () => __TAURI_INVOKE<number[]>("get_processors_usage"),
	// ## Get GPU temperature
	getGpuTemperature: () => typedError<NameValue[], string>(__TAURI_INVOKE("get_gpu_temperature")),
	/**
	 *  ## Get CPU usage history
	 * 
	 *  - param state: shared `HistoryStore`.
	 *  - param seconds: `u32` Number of seconds to retrieve
	 */
	getCpuUsageHistory: (seconds: number) => __TAURI_INVOKE<number[]>("get_cpu_usage_history", { seconds }),
	/**
	 *  ## Get memory usage history
	 * 
	 *  - param state: shared `HistoryStore`.
	 *  - param seconds: `u32` Number of seconds to retrieve
	 */
	getMemoryUsageHistory: (seconds: number) => __TAURI_INVOKE<number[]>("get_memory_usage_history", { seconds }),
	/**
	 *  ## Get GPU usage history
	 * 
	 *  - param state: shared `HistoryStore`.
	 *  - param gpu_id: `String` GPU identifier (e.g. "nvapi:0")
	 *  - param seconds: `u32` Number of seconds to retrieve
	 */
	getGpuUsageHistory: (gpuId: string, seconds: number) => __TAURI_INVOKE<number[]>("get_gpu_usage_history", { gpuId, seconds }),
	// ## Get network information
	getNetworkInfo: () => typedError<NetworkInfo[], BackendError>(__TAURI_INVOKE("get_network_info")),
	/**
	 *  ## Get Super I/O chip-id diagnostics through PawnIO LpcIO
	 * 
	 *  This diagnostic only reads raw chip-id registers (`0x20` / `0x21`) after
	 *  the documented Nuvoton and ITE configuration-mode enter sequences. It does
	 *  not read temperatures, fan counters, voltages, or any hardware-monitor data.
	 */
	getSuperIoChipIdDiagnostics: () => typedError<SuperIoChipIdDiagnostics, string>(__TAURI_INVOKE("get_super_io_chip_id_diagnostics")),
	/**
	 *  ## Get realtime GPU memory usage (best-effort)
	 * 
	 *  **Platform support**: Currently implemented only on macOS. On other
	 *  platforms, or where the underlying APIs are not available, this will
	 *  return `Ok(None)` instead of failing.
	 */
	getGpuMemoryUsage: () => typedError<{
	inUseBytes: string | null,
	allocBytes: string | null,
} | null, string>(__TAURI_INVOKE("get_gpu_memory_usage")),
	// ## Get latest Storage Health records for the dashboard
	getStorageHealthLatestRecords: () => typedError<StorageHealthRecord[], string>(__TAURI_INVOKE("get_storage_health_latest_records")),
	/**
	 *  ## Get Live Storage Health signals (on demand, never persisted — ADR 0006)
	 * 
	 *  Reads the startup-cached device list with one `DeviceIoControl` query
	 *  per device; repeated calls within the core-side minimum interval
	 *  return the last reading. Returns an empty list when
	 *  `storageHealth.enabled` is off or on platforms without the cheap
	 *  native read path (displays fall back to the daily records).
	 */
	getLiveStorageHealth: () => typedError<LiveStorageHealth[], string>(__TAURI_INVOKE("get_live_storage_health")),
	/**
	 *  ## Re-detect Storage Devices
	 * 
	 *  Re-detects connected storage devices, refreshes the Live Storage
	 *  Health cache, collects current Storage Health signals, updates
	 *  today's Storage Health Records, and returns the latest active records
	 *  for the dashboard.
	 */
	refreshStorageDevices: () => typedError<StorageHealthRecord[], string>(__TAURI_INVOKE("refresh_storage_devices")),
	getExternalComponentGuidanceCandidates: (view: ExternalComponentGuidanceView) => typedError<ExternalComponentGuidanceCandidate[], string>(__TAURI_INVOKE("get_external_component_guidance_candidates", { view })),
	deferExternalComponentGuidanceForSession: (key: string) => typedError<null, string>(__TAURI_INVOKE("defer_external_component_guidance_for_session", { key })),
	// ## Get archived CPU/RAM records
	getDataArchiveRecords: (hardwareType: DataArchiveHardwareType, dataStats: ArchiveDataStats, start: string, end: string) => typedError<ArchiveRecord[], string>(__TAURI_INVOKE("get_data_archive_records", { hardwareType, dataStats, start, end })),
	// ## Get archived GPU records
	getGpuArchiveRecords: (dataType: GpuArchiveDataType, dataStats: ArchiveDataStats, gpuName: string, start: string, end: string) => typedError<ArchiveRecord[], string>(__TAURI_INVOKE("get_gpu_archive_records", { dataType, dataStats, gpuName, start, end })),
	// ## Get archived process stats for a period ending at `end_at`
	getProcessStats: (period: number, endAt: string) => typedError<ProcessStatRecord[], string>(__TAURI_INVOKE("get_process_stats", { period, endAt })),
	// ## Get archived process stats between two timestamps
	getProcessStatsInPeriod: (start: string, end: string) => typedError<ProcessStatRecord[], string>(__TAURI_INVOKE("get_process_stats_in_period", { start, end })),
	// ## Get GPU names that have archive records
	getGpuArchiveNames: () => typedError<string[], string>(__TAURI_INVOKE("get_gpu_archive_names")),
	getSettings: () => typedError<ClientSettings_Serialize, string>(__TAURI_INVOKE("get_settings")),
	setLanguage: (newLanguage: string) => typedError<null, string>(__TAURI_INVOKE("set_language", { newLanguage })),
	setTheme: (newTheme: Theme) => typedError<null, string>(__TAURI_INVOKE("set_theme", { newTheme })),
	setNavigationLayout: (newLayout: NavigationLayout) => typedError<null, string>(__TAURI_INVOKE("set_navigation_layout", { newLayout })),
	acknowledgeNavigationRestructureAnnouncement: () => typedError<null, string>(__TAURI_INVOKE("acknowledge_navigation_restructure_announcement")),
	setDisplayTargets: (newTargets: HardwareType[]) => typedError<null, string>(__TAURI_INVOKE("set_display_targets", { newTargets })),
	setGraphSize: (newSize: GraphSize) => typedError<null, string>(__TAURI_INVOKE("set_graph_size", { newSize })),
	setGraphFitToWindow: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_graph_fit_to_window", { newValue })),
	setGraphMarginPx: (newValue: number) => typedError<null, string>(__TAURI_INVOKE("set_graph_margin_px", { newValue })),
	setLineGraphType: (newType: LineGraphType) => typedError<null, string>(__TAURI_INVOKE("set_line_graph_type", { newType })),
	setLineGraphBorder: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_line_graph_border", { newValue })),
	setLineGraphFill: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_line_graph_fill", { newValue })),
	setLineGraphColor: (target: HardwareType, newColor: string) => typedError<string, string>(__TAURI_INVOKE("set_line_graph_color", { target, newColor })),
	setLineGraphMix: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_line_graph_mix", { newValue })),
	setLineGraphShowLegend: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_line_graph_show_legend", { newValue })),
	setLineGraphShowScale: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_line_graph_show_scale", { newValue })),
	setLineGraphShowTooltip: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_line_graph_show_tooltip", { newValue })),
	setBackgroundImgOpacity: (newValue: number) => typedError<null, string>(__TAURI_INVOKE("set_background_img_opacity", { newValue })),
	setSelectedBackgroundImg: (fileId: string | null) => typedError<null, string>(__TAURI_INVOKE("set_selected_background_img", { fileId })),
	setTransparentUi: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_transparent_ui", { newValue })),
	setWindowOpacity: (newValue: number) => typedError<null, string>(__TAURI_INVOKE("set_window_opacity", { newValue })),
	setGlassBlur: (newValue: number) => typedError<null, string>(__TAURI_INVOKE("set_glass_blur", { newValue })),
	setTemperatureUnit: (newUnit: TemperatureUnit) => typedError<null, string>(__TAURI_INVOKE("set_temperature_unit", { newUnit })),
	setHardwareArchiveEnabled: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_hardware_archive_enabled", { newValue })),
	setHardwareArchiveRetentionDays: (newRetentionDays: number) => typedError<null, string>(__TAURI_INVOKE("set_hardware_archive_retention_days", { newRetentionDays })),
	setHardwareArchiveScheduledDataDeletion: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_hardware_archive_scheduled_data_deletion", { newValue })),
	setStorageHealthRetentionDays: (newRetentionDays: number) => typedError<null, string>(__TAURI_INVOKE("set_storage_health_retention_days", { newRetentionDays })),
	setBurnInShift: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_burn_in_shift", { newValue })),
	setBurnInShiftMode: (newValue: BurnInShiftMode) => typedError<null, string>(__TAURI_INVOKE("set_burn_in_shift_mode", { newValue })),
	setBurnInShiftPreset: (newValue: BurnInShiftPreset) => typedError<null, string>(__TAURI_INVOKE("set_burn_in_shift_preset", { newValue })),
	setBurnInShiftIdleOnly: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_burn_in_shift_idle_only", { newValue })),
	setBurnInShiftOptions: (newValue: {
	// Override interval (ms) for jump
	intervalMs?: number | null,
	// Override amplitude (px) for jump [x, y]
	amplitudePx?: [number, number] | null,
	// Idle threshold in ms
	idleThresholdMs?: number | null,
	// Drift cycle duration (sec)
	driftDurationSec?: number | null,
} | null) => typedError<null, string>(__TAURI_INVOKE("set_burn_in_shift_options", { newValue })),
	setTextSelectable: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_text_selectable", { newValue })),
	setTrayWidgetSettings: (newValue: TrayWidgetSettings_Deserialize) => typedError<null, string>(__TAURI_INVOKE("set_tray_widget_settings", { newValue })),
	setCloseToTrayPreference: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_close_to_tray_preference", { newValue })),
	acknowledgeExternalComponentGuidanceKey: (key: string) => typedError<null, string>(__TAURI_INVOKE("acknowledge_external_component_guidance_key", { key })),
	setElevatedStartupMode: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_elevated_startup_mode", { newValue })),
	readLicenseFile: () => typedError<string, string>(__TAURI_INVOKE("read_license_file")),
	readThirdPartyNoticesFile: () => typedError<string, string>(__TAURI_INVOKE("read_third_party_notices_file")),
	openLicenseFilePath: () => typedError<null, string>(__TAURI_INVOKE("open_license_file_path")),
	/**
	 *  Get background image
	 * 
	 *  - `file_id`: Image file ID
	 */
	getBackgroundImage: (fileId: string) => typedError<string, string>(__TAURI_INVOKE("get_background_image", { fileId })),
	// Get list of background images in BG_IMG_DIR_NAME directory
	getBackgroundImages: () => typedError<BackgroundImage[], string>(__TAURI_INVOKE("get_background_images")),
	/**
	 *  Save background image
	 * 
	 *  - `image_data`: Base64 string of image data
	 *  - returns: `file_id`
	 * 
	 *  ### TODO
	 *  - Use JsImage https://docs.rs/tauri/2.1.1/tauri/image/enum.JsImage.html
	 *    - Implemented with Base64 for now as type definition with specta was difficult
	 * 
	 */
	saveBackgroundImage: (imageData: string) => typedError<string, string>(__TAURI_INVOKE("save_background_image", { imageData })),
	/**
	 *  Delete background image
	 *  - `file_id`: Image file ID
	 */
	deleteBackgroundImage: (fileId: string) => typedError<null, string>(__TAURI_INVOKE("delete_background_image", { fileId })),
	// Set window decoration state
	setDecoration: (isDecorated: boolean) => typedError<null, string>(__TAURI_INVOKE("set_decoration", { isDecorated })),
	// Restart the application
	restartApp: () => __TAURI_INVOKE<void>("restart_app"),
	// Returns whether the current process is running with administrator privileges.
	isProcessElevated: () => typedError<boolean, string>(__TAURI_INVOKE("is_process_elevated")),
	/**
	 *  Stop monitoring and exit the process.
	 * 
	 *  Phase 5 (#1408): the explicit Quit path. Keep it gated to the
	 *  internal callers that the lifecycle module owns — Phase 6's tray
	 *  menu and the future "Quit" UX from #1275. Until those land, this
	 *  command is reachable only from devtools / tauri-specta-generated
	 *  bindings, which is enough to validate the cleanup ordering.
	 */
	quitApp: () => __TAURI_INVOKE<void>("quit_app"),
	// Returns whether close-to-tray can safely be enabled in this session.
	isCloseToTrayAvailable: () => typedError<boolean, string>(__TAURI_INVOKE("is_close_to_tray_available")),
	// Mark the frontend close-to-tray dialog listener as ready.
	markCloseToTrayListenerReady: () => typedError<null, string>(__TAURI_INVOKE("mark_close_to_tray_listener_ready")),
};

/** Events */
export const events = {
	hardwareMonitorUpdate: makeEvent<HardwareMonitorUpdate>("hardware-monitor-update"),
};

/* Types */
export type ArchiveDataStats = "avg" | "max" | "min";

export type ArchiveRecord = {
	id: number,
	value: number | null,
	timestamp: string,
};

export type BackendError = "cpuInfoNotAvailable" | "storageInfoNotAvailable" | "memoryInfoNotAvailable" | "graphicInfoNotAvailable" | "networkInfoNotAvailable" | "networkUsageNotAvailable" | "unexpectedError";

/**
 *  - `file_id` : Image file ID
 *  - `image_data` : Base64 string of image data
 */
export type BackgroundImage = {
	fileId: string,
	imageData: string,
};

export type BurnInShiftMode = "jump" | "drift";

export type BurnInShiftOptions = {
	// Override interval (ms) for jump
	intervalMs?: number | null,
	// Override amplitude (px) for jump [x, y]
	amplitudePx?: [number, number] | null,
	// Idle threshold in ms
	idleThresholdMs?: number | null,
	// Drift cycle duration (sec)
	driftDurationSec?: number | null,
};

export type BurnInShiftPreset = "gentle" | "balanced" | "aggressive";

export type ClientSettings = ClientSettings_Serialize | ClientSettings_Deserialize;

export type ClientSettings_Deserialize = {
	version: string,
	language: string,
	theme: Theme,
	navigationLayout: NavigationLayout,
	lastAcknowledgedAnnouncement: string | null,
	displayTargets: HardwareType[],
	graphSize: GraphSize,
	graphFitToWindow: boolean,
	graphMarginPx: number,
	lineGraphType: LineGraphType,
	lineGraphBorder: boolean,
	lineGraphFill: boolean,
	lineGraphColor: LineGraphColorStringSettings,
	lineGraphMix: boolean,
	lineGraphShowLegend: boolean,
	lineGraphShowScale: boolean,
	lineGraphShowTooltip: boolean,
	backgroundImgOpacity: number,
	selectedBackgroundImg: string | null,
	transparentUi: boolean,
	windowOpacity: number,
	glassBlur: number,
	temperatureUnit: TemperatureUnit,
	hardwareArchive: HardwareArchiveSettings,
	storageHealth: StorageHealthSettings,
	burnInShift: boolean,
	burnInShiftMode: BurnInShiftMode,
	burnInShiftPreset: BurnInShiftPreset,
	burnInShiftIdleOnly: boolean,
	burnInShiftOptions: BurnInShiftOptions | null,
	textSelectable: boolean,
	closeToTray: boolean,
	closeToTrayChoiceMade: boolean,
	externalComponentGuidance: ExternalComponentGuidanceSettings,
	elevatedStartupMode: boolean,
	trayWidget: TrayWidgetSettings_Deserialize,
};

export type ClientSettings_Serialize = {
	version: string,
	language: string,
	theme: Theme,
	navigationLayout: NavigationLayout,
	lastAcknowledgedAnnouncement: string | null,
	displayTargets: HardwareType[],
	graphSize: GraphSize,
	graphFitToWindow: boolean,
	graphMarginPx: number,
	lineGraphType: LineGraphType,
	lineGraphBorder: boolean,
	lineGraphFill: boolean,
	lineGraphColor: LineGraphColorStringSettings,
	lineGraphMix: boolean,
	lineGraphShowLegend: boolean,
	lineGraphShowScale: boolean,
	lineGraphShowTooltip: boolean,
	backgroundImgOpacity: number,
	selectedBackgroundImg: string | null,
	transparentUi: boolean,
	windowOpacity: number,
	glassBlur: number,
	temperatureUnit: TemperatureUnit,
	hardwareArchive: HardwareArchiveSettings,
	storageHealth: StorageHealthSettings,
	burnInShift: boolean,
	burnInShiftMode: BurnInShiftMode,
	burnInShiftPreset: BurnInShiftPreset,
	burnInShiftIdleOnly: boolean,
	burnInShiftOptions: BurnInShiftOptions | null,
	textSelectable: boolean,
	closeToTray: boolean,
	closeToTrayChoiceMade: boolean,
	externalComponentGuidance: ExternalComponentGuidanceSettings,
	elevatedStartupMode: boolean,
	trayWidget: TrayWidgetSettings_Serialize,
};

export type CpuInfo = {
	name: string,
	vendor: string,
	coreCount: number,
	clock: number,
	clockUnit: string,
	cpuName: string,
};

export type DataArchiveHardwareType = "cpu" | "memory";

export type DiskKind = "hdd" | "ssd" | "other";

export type DownloadEvent = { event: "started"; data: {
	contentLength: string | null,
} } | { event: "progress"; data: {
	chunkLength: string,
} } | { event: "finished" };

export type ExternalComponent = "pawnio" | "smartctl";

export type ExternalComponentGuidanceCandidate = {
	key: string,
	component: ExternalComponent,
	usage: ExternalComponentUsage,
	reasonKind: ExternalComponentReasonKind,
	missingSignals: string[],
	affectedDeviceCount: number | null,
	diagnosticDetail: string | null,
};

export type ExternalComponentGuidanceSettings = {
	acknowledgedKeys?: string[],
};

export type ExternalComponentGuidanceView = "dashboard" | "cpuDetail" | "storageHealth";

export type ExternalComponentReasonKind = "missing" | "permission" | "misconfigured" | "failed";

export type ExternalComponentUsage = "cpuPackageTemperature" | "motherboardSensors" | "storageHealth";

export type FanSpeedStatus = "active" | "inactive" | "invalid";

export type GpuArchiveDataType = "usage" | "temp" | "dedicatedMemory";

export type GpuMemoryUsage = {
	inUseBytes: string | null,
	allocBytes: string | null,
};

export type GpuMonitorData = {
	gpuId: string,
	gpuName: string,
	gpuUsage: number | null,
	gpuTemperature: number | null,
	gpuSource: string,
	gpuDedicatedMemoryUsageKb: number | null,
	gpuCoolerLevel: number | null,
};

export type GpuUsageResult = {
	usage: number,
	source: string,
};

export type GraphSize = "sm" | "md" | "lg" | "xl" | "2xl";

export type GraphicInfo = {
	id: string,
	name: string,
	vendorName: string,
	clock: number,
	memorySize: string,
	memorySizeDedicated: string,
	coreCount: string | null,
};

/**
 *  Wire-format mirror of [`hardviz_core::settings::HardwareArchiveSettings`].
 * 
 *  The canonical definition lives in `hardviz_core::settings` so the
 *  archive worker (and any future Core consumer) doesn't need to know
 *  about Tauri or specta. This App-side struct exists only because the
 *  frontend wire format requires `specta::Type`.
 */
export type HardwareArchiveSettings = {
	enabled?: boolean,
	scheduledDataDeletion?: boolean,
	retentionDays?: number,
};

export type HardwareMonitorUpdate = {
	cpuUsage: number,
	memoryUsage: number,
	gpus: GpuMonitorData[],
	processorsUsage: number[],
	// Headline CPU temperature in the user's preferred unit. Currently Windows only.
	cpuTemperature: number | null,
	// All named temperature sensors (thermal zones) in the user's preferred unit.
	sensorTemperatures: NameValue[],
	// Motherboard temperature sensors in the user's preferred unit.
	motherboardTemperatures: MotherboardTemperatureValue[],
	// Motherboard fan speeds in RPM.
	motherboardFanSpeeds: MotherboardFanSpeedValue[],
};

export type HardwareType = "cpu" | "memory" | "gpu";

// Structure of settings to send to client
export type LineGraphColorStringSettings = {
	cpu: string,
	memory: string,
	gpu: string,
};

export type LineGraphType = "default" | "step" | "linear" | "basis";

export type LiveStorageHealth = {
	deviceId: string,
	displayName: string,
	temperatureCelsius: number | null,
	availableSparePercent: number | null,
	percentageUsed: number | null,
	mediaErrors: number | null,
	unsafeShutdownCount: number | null,
	powerOnHours: number | null,
	powerCycleCount: number | null,
	collectedAt: string,
};

export type MemoryInfo = {
	size: string,
	clock: number,
	clockUnit: string,
	memoryCount: number,
	totalSlots: number,
	memoryType: string,
	isDetailed: boolean,
};

export type MotherboardFanSpeedValue = {
	name: string,
	rpm: number | null,
	status: FanSpeedStatus,
	source: string,
};

export type MotherboardInfo = {
	manufacturer: string,
	product: string,
	version: string,
	serialNumber: string,
	biosVendor: string,
	biosVersion: string,
	biosReleaseDate: string,
};

export type MotherboardTemperatureValue = {
	name: string,
	value: number,
	source: string,
};

export type NameValue = {
	name: string,
	value: number,
};

export type NavigationLayout = "grouped" | "classic";

export type NetworkInfo = {
	description: string | null,
	macAddress: string | null,
	ipv4: string[],
	ipv6: string[],
	linkLocalIpv6: string[],
	ipSubnet: string[],
	defaultIpv4Gateway: string[],
	defaultIpv6Gateway: string[],
};

export type PawnIoRuntimeDiagnostics = {
	installLocation: string | null,
	dllPath: string | null,
	modulePath: string | null,
	pawnioAvailable: boolean,
	libraryLoadable: boolean,
	driverOpenable: boolean,
	moduleLoadable: boolean,
	version: number | null,
	fallbackReason: string | null,
};

export type ProcessInfo = ProcessInfo_Serialize | ProcessInfo_Deserialize;

export type ProcessInfo_Deserialize = {
	pid: number,
	name: string,
	cpuUsage: string,
	memoryUsage: string,
};

export type ProcessInfo_Serialize = {
	pid: number,
	name: string,
	cpuUsage: string,
	memoryUsage: string,
};

export type ProcessStatRecord = {
	pid: number,
	process_name: string,
	avg_cpu_usage: number,
	avg_memory_usage: number,
	total_execution_sec: number,
	latest_timestamp: string,
};

export type SizeUnit = "B" | "KB" | "MB" | "GB";

export type StorageHealthRecord = {
	deviceId: string,
	displayName: string,
	model: string | null,
	protocol: string | null,
	capacityBytes: number | null,
	date: string,
	healthStatus: StorageHealthStatus,
	warningLevel: StorageWarningLevel,
	temperatureCelsius: number | null,
	powerOnHours: number | null,
	percentageUsed: number | null,
	availableSparePercent: number | null,
	reallocatedSectorCount: number | null,
	currentPendingSectorCount: number | null,
	offlineUncorrectableCount: number | null,
	mediaErrors: number | null,
	errorLogEntries: number | null,
	unsafeShutdownCount: number | null,
	warningReasons: string[],
	collectedAt: string,
};

/**
 *  Wire-format mirror of [`hardviz_core::settings::StorageHealthSettings`]. The
 *  canonical definition lives in `hardviz_core::settings` so the
 *  storage health record worker doesn't need to know about Tauri or specta.
 */
export type StorageHealthSettings = {
	enabled?: boolean,
	retentionDays?: number,
};

export type StorageHealthStatus = "good" | "warning" | "critical" | "unknown";

export type StorageInfo = {
	name: string,
	size: number,
	sizeUnit: SizeUnit,
	free: number,
	freeUnit: SizeUnit,
	storageType: DiskKind,
	fileSystem: string,
};

export type StorageWarningLevel = "none" | "warning" | "critical" | "unknown";

export type SuperIoChipIdAttempt = {
	vendor: SuperIoVendor,
	idHigh: number | null,
	idLow: number | null,
	chipId: number | null,
	absent: boolean,
	error: string | null,
	exitError: string | null,
};

export type SuperIoChipIdDiagnostics = {
	platformSupported: boolean,
	pawnio: PawnIoRuntimeDiagnostics | null,
	slots: SuperIoChipIdSlotProbe[],
	error: string | null,
};

export type SuperIoChipIdSlotProbe = {
	slot: number,
	indexPort: number,
	dataPort: number,
	attempts: SuperIoChipIdAttempt[],
	error: string | null,
};

export type SuperIoVendor = "nuvoton" | "ite";

export type SysInfo = {
	cpu: CpuInfo | null,
	memory: MemoryInfo | null,
	gpus: GraphicInfo[] | null,
	storage: StorageInfo[],
	motherboard: MotherboardInfo | null,
};

export type TemperatureUnit = "C" | "F";

export type Theme = "system" | "light" | "dark" | "darkPlus" | "sky" | "grove" | "sunset" | "nebula" | "orbit" | "cappuccino" | "espresso";

export type TrayMetric = "cpu" | "gpu" | "gpu-temp";

export type TrayWidgetSettings = TrayWidgetSettings_Serialize | TrayWidgetSettings_Deserialize;

export type TrayWidgetSettings_Deserialize = {
	enabled?: boolean,
	metricOrder?: TrayMetric[],
	visibleMetrics?: TrayMetric[],
	updateIntervalSecs?: number,
	metrics?: TrayMetric[],
};

export type TrayWidgetSettings_Serialize = {
	enabled: boolean,
	metricOrder: TrayMetric[],
	visibleMetrics: TrayMetric[],
	updateIntervalSecs: number,
};

export type UpdateMetadata = {
	version: string,
	currentVersion: string,
	notes: string | null,
	pubDate: string | null,
};

export type UpdaterError = "NoPendingUpdate" | { Updater: string };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    void _assertTypedErrorFollowsContract;
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        return { status: "error", error: e as E };
    }
}
// @ts-expect-error tauri-specta's generated contract assertion leaves E unused under noUnusedLocals.


const _assertTypedErrorFollowsContract: <T, E>(result: Promise<T>) => Promise<any> = typedError;

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

