// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	// Fetch available update metadata
	fetchUpdate: () => typedError<{
	version: string,
	currentVersion: string,
	notes: string | null,
	pubDate: string | null,
} | null, UpdaterError>(__TAURI_INVOKE("fetch_update")),
	// Install the pending update
	installUpdate: (onEvent: Channel<DownloadEvent>) => typedError<null, UpdaterError>(__TAURI_INVOKE("install_update", { onEvent })),
	// ## Get process list
	getProcessList: () => __TAURI_INVOKE<ProcessInfo_Serialize[]>("get_process_list"),
	/**
	 *  ## Get CPU usage (%)
	 * 
	 *  - param state: shared `HistoryStore` from the Core collector.
	 *  - return: `i32` overall CPU usage (%)
	 */
	getCpuUsage: () => __TAURI_INVOKE<number>("get_cpu_usage"),
	// ## Get system information
	getHardwareInfo: () => typedError<SysInfo, string>(__TAURI_INVOKE("get_hardware_info")),
	/**
	 *  ## Get detailed memory information
	 * 
	 *  - return: `models::hardware::MemoryInfo` Detailed memory information
	 */
	getMemoryInfoDetail: () => typedError<MemoryInfo, string>(__TAURI_INVOKE("get_memory_info_detail")),
	/**
	 *  ## Get memory usage (%)
	 * 
	 *  - param state: shared `HistoryStore`.
	 *  - return: `i32` Memory usage (%)
	 */
	getMemoryUsage: () => __TAURI_INVOKE<number>("get_memory_usage"),
	/**
	 *  ## Get GPU usage (%)
	 * 
	 *  Returns the GPU usage percentage together with the data-source
	 *  identifier (e.g. "NVAPI", "ADL", "PDH", "DRM (AMD)", "IOKit").
	 */
	getGpuUsage: () => typedError<GpuUsageResult, string>(__TAURI_INVOKE("get_gpu_usage")),
	getProcessorsUsage: () => __TAURI_INVOKE<number[]>("get_processors_usage"),
	// ## Get GPU temperature
	getGpuTemperature: () => typedError<NameValue[], string>(__TAURI_INVOKE("get_gpu_temperature")),
	/**
	 *  ## Get CPU usage history
	 * 
	 *  - param state: shared `HistoryStore`.
	 *  - param seconds: `u32` Number of seconds to retrieve
	 */
	getCpuUsageHistory: (seconds: number) => __TAURI_INVOKE<number[]>("get_cpu_usage_history", { seconds }),
	/**
	 *  ## Get memory usage history
	 * 
	 *  - param state: shared `HistoryStore`.
	 *  - param seconds: `u32` Number of seconds to retrieve
	 */
	getMemoryUsageHistory: (seconds: number) => __TAURI_INVOKE<number[]>("get_memory_usage_history", { seconds }),
	/**
	 *  ## Get GPU usage history
	 * 
	 *  - param state: shared `HistoryStore`.
	 *  - param gpu_id: `String` GPU identifier (e.g. "nvapi:0")
	 *  - param seconds: `u32` Number of seconds to retrieve
	 */
	getGpuUsageHistory: (gpuId: string, seconds: number) => __TAURI_INVOKE<number[]>("get_gpu_usage_history", { gpuId, seconds }),
	// ## Get network information
	getNetworkInfo: () => typedError<NetworkInfo[], BackendError>(__TAURI_INVOKE("get_network_info")),
	/**
	 *  ## Get realtime GPU memory usage (best-effort)
	 * 
	 *  **Platform support**: Currently implemented only on macOS. On other
	 *  platforms, or where the underlying APIs are not available, this will
	 *  return `Ok(None)` instead of failing.
	 */
	getGpuMemoryUsage: () => typedError<{
	inUseBytes: string | null,
	allocBytes: string | null,
} | null, string>(__TAURI_INVOKE("get_gpu_memory_usage")),
	// ## Get latest Storage SMART snapshots for the dashboard
	getStorageSmartLatestSnapshots: () => typedError<StorageSmartDashboardSnapshot[], string>(__TAURI_INVOKE("get_storage_smart_latest_snapshots")),
	getSettings: () => typedError<ClientSettings_Serialize, string>(__TAURI_INVOKE("get_settings")),
	setLanguage: (newLanguage: string) => typedError<null, string>(__TAURI_INVOKE("set_language", { newLanguage })),
	setTheme: (newTheme: Theme) => typedError<null, string>(__TAURI_INVOKE("set_theme", { newTheme })),
	setDisplayTargets: (newTargets: HardwareType[]) => typedError<null, string>(__TAURI_INVOKE("set_display_targets", { newTargets })),
	setGraphSize: (newSize: GraphSize) => typedError<null, string>(__TAURI_INVOKE("set_graph_size", { newSize })),
	setLineGraphType: (newType: LineGraphType) => typedError<null, string>(__TAURI_INVOKE("set_line_graph_type", { newType })),
	setLineGraphBorder: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_line_graph_border", { newValue })),
	setLineGraphFill: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_line_graph_fill", { newValue })),
	setLineGraphColor: (target: HardwareType, newColor: string) => typedError<string, string>(__TAURI_INVOKE("set_line_graph_color", { target, newColor })),
	setLineGraphMix: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_line_graph_mix", { newValue })),
	setLineGraphShowLegend: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_line_graph_show_legend", { newValue })),
	setLineGraphShowScale: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_line_graph_show_scale", { newValue })),
	setLineGraphShowTooltip: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_line_graph_show_tooltip", { newValue })),
	setBackgroundImgOpacity: (newValue: number) => typedError<null, string>(__TAURI_INVOKE("set_background_img_opacity", { newValue })),
	setSelectedBackgroundImg: (fileId: string | null) => typedError<null, string>(__TAURI_INVOKE("set_selected_background_img", { fileId })),
	setTransparentUi: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_transparent_ui", { newValue })),
	setWindowOpacity: (newValue: number) => typedError<null, string>(__TAURI_INVOKE("set_window_opacity", { newValue })),
	setTemperatureUnit: (newUnit: TemperatureUnit) => typedError<null, string>(__TAURI_INVOKE("set_temperature_unit", { newUnit })),
	setHardwareArchiveEnabled: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_hardware_archive_enabled", { newValue })),
	setHardwareArchiveRetentionDays: (newRetentionDays: number) => typedError<null, string>(__TAURI_INVOKE("set_hardware_archive_retention_days", { newRetentionDays })),
	setHardwareArchiveScheduledDataDeletion: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_hardware_archive_scheduled_data_deletion", { newValue })),
	setStorageSmartRetentionDays: (newRetentionDays: number) => typedError<null, string>(__TAURI_INVOKE("set_storage_smart_retention_days", { newRetentionDays })),
	setBurnInShift: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_burn_in_shift", { newValue })),
	setBurnInShiftMode: (newValue: BurnInShiftMode) => typedError<null, string>(__TAURI_INVOKE("set_burn_in_shift_mode", { newValue })),
	setBurnInShiftPreset: (newValue: BurnInShiftPreset) => typedError<null, string>(__TAURI_INVOKE("set_burn_in_shift_preset", { newValue })),
	setBurnInShiftIdleOnly: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_burn_in_shift_idle_only", { newValue })),
	setBurnInShiftOptions: (newValue: {
	// Override interval (ms) for jump
	intervalMs?: number | null,
	// Override amplitude (px) for jump [x, y]
	amplitudePx?: [number, number] | null,
	// Idle threshold in ms
	idleThresholdMs?: number | null,
	// Drift cycle duration (sec)
	driftDurationSec?: number | null,
} | null) => typedError<null, string>(__TAURI_INVOKE("set_burn_in_shift_options", { newValue })),
	setTextSelectable: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_text_selectable", { newValue })),
	setTrayWidgetSettings: (newValue: TrayWidgetSettings_Deserialize) => typedError<null, string>(__TAURI_INVOKE("set_tray_widget_settings", { newValue })),
	setCloseToTrayPreference: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_close_to_tray_preference", { newValue })),
	readLicenseFile: () => typedError<string, string>(__TAURI_INVOKE("read_license_file")),
	readThirdPartyNoticesFile: () => typedError<string, string>(__TAURI_INVOKE("read_third_party_notices_file")),
	openLicenseFilePath: () => typedError<null, string>(__TAURI_INVOKE("open_license_file_path")),
	/**
	 *  Get background image
	 * 
	 *  - `file_id`: Image file ID
	 */
	getBackgroundImage: (fileId: string) => typedError<string, string>(__TAURI_INVOKE("get_background_image", { fileId })),
	// Get list of background images in BG_IMG_DIR_NAME directory
	getBackgroundImages: () => typedError<BackgroundImage[], string>(__TAURI_INVOKE("get_background_images")),
	/**
	 *  Save background image
	 * 
	 *  - `image_data`: Base64 string of image data
	 *  - returns: `file_id`
	 * 
	 *  ### TODO
	 *  - Use JsImage https://docs.rs/tauri/2.1.1/tauri/image/enum.JsImage.html
	 *    - Implemented with Base64 for now as type definition with specta was difficult
	 * 
	 */
	saveBackgroundImage: (imageData: string) => typedError<string, string>(__TAURI_INVOKE("save_background_image", { imageData })),
	/**
	 *  Delete background image
	 *  - `file_id`: Image file ID
	 */
	deleteBackgroundImage: (fileId: string) => typedError<null, string>(__TAURI_INVOKE("delete_background_image", { fileId })),
	// Set window decoration state
	setDecoration: (isDecorated: boolean) => typedError<null, string>(__TAURI_INVOKE("set_decoration", { isDecorated })),
	// Restart the application
	restartApp: () => __TAURI_INVOKE<void>("restart_app"),
	/**
	 *  Stop monitoring and exit the process.
	 * 
	 *  Phase 5 (#1408): the explicit Quit path. Keep it gated to the
	 *  internal callers that the lifecycle module owns — Phase 6's tray
	 *  menu and the future "Quit" UX from #1275. Until those land, this
	 *  command is reachable only from devtools / tauri-specta-generated
	 *  bindings, which is enough to validate the cleanup ordering.
	 */
	quitApp: () => __TAURI_INVOKE<void>("quit_app"),
	// Returns whether close-to-tray can safely be enabled in this session.
	isCloseToTrayAvailable: () => typedError<boolean, string>(__TAURI_INVOKE("is_close_to_tray_available")),
	// Mark the frontend close-to-tray dialog listener as ready.
	markCloseToTrayListenerReady: () => typedError<null, string>(__TAURI_INVOKE("mark_close_to_tray_listener_ready")),
};

/** Events */
export const events = {
	hardwareMonitorUpdate: makeEvent<HardwareMonitorUpdate>("hardware-monitor-update"),
};

/* Types */
export type BackendError = "cpuInfoNotAvailable" | "storageInfoNotAvailable" | "memoryInfoNotAvailable" | "graphicInfoNotAvailable" | "networkInfoNotAvailable" | "networkUsageNotAvailable" | "unexpectedError";

/**
 *  - `file_id` : Image file ID
 *  - `image_data` : Base64 string of image data
 */
export type BackgroundImage = {
	fileId: string,
	imageData: string,
};

export type BurnInShiftMode = "jump" | "drift";

export type BurnInShiftOptions = {
	// Override interval (ms) for jump
	intervalMs?: number | null,
	// Override amplitude (px) for jump [x, y]
	amplitudePx?: [number, number] | null,
	// Idle threshold in ms
	idleThresholdMs?: number | null,
	// Drift cycle duration (sec)
	driftDurationSec?: number | null,
};

export type BurnInShiftPreset = "gentle" | "balanced" | "aggressive";

export type ClientSettings = ClientSettings_Serialize | ClientSettings_Deserialize;

export type ClientSettings_Deserialize = {
	version: string,
	language: string,
	theme: Theme,
	displayTargets: HardwareType[],
	graphSize: GraphSize,
	lineGraphType: LineGraphType,
	lineGraphBorder: boolean,
	lineGraphFill: boolean,
	lineGraphColor: LineGraphColorStringSettings,
	lineGraphMix: boolean,
	lineGraphShowLegend: boolean,
	lineGraphShowScale: boolean,
	lineGraphShowTooltip: boolean,
	backgroundImgOpacity: number,
	selectedBackgroundImg: string | null,
	transparentUi: boolean,
	windowOpacity: number,
	temperatureUnit: TemperatureUnit,
	hardwareArchive: HardwareArchiveSettings,
	storageSmart: StorageSmartSettings,
	burnInShift: boolean,
	burnInShiftMode: BurnInShiftMode,
	burnInShiftPreset: BurnInShiftPreset,
	burnInShiftIdleOnly: boolean,
	burnInShiftOptions: BurnInShiftOptions | null,
	textSelectable: boolean,
	closeToTray: boolean,
	closeToTrayChoiceMade: boolean,
	trayWidget: TrayWidgetSettings_Deserialize,
};

export type ClientSettings_Serialize = {
	version: string,
	language: string,
	theme: Theme,
	displayTargets: HardwareType[],
	graphSize: GraphSize,
	lineGraphType: LineGraphType,
	lineGraphBorder: boolean,
	lineGraphFill: boolean,
	lineGraphColor: LineGraphColorStringSettings,
	lineGraphMix: boolean,
	lineGraphShowLegend: boolean,
	lineGraphShowScale: boolean,
	lineGraphShowTooltip: boolean,
	backgroundImgOpacity: number,
	selectedBackgroundImg: string | null,
	transparentUi: boolean,
	windowOpacity: number,
	temperatureUnit: TemperatureUnit,
	hardwareArchive: HardwareArchiveSettings,
	storageSmart: StorageSmartSettings,
	burnInShift: boolean,
	burnInShiftMode: BurnInShiftMode,
	burnInShiftPreset: BurnInShiftPreset,
	burnInShiftIdleOnly: boolean,
	burnInShiftOptions: BurnInShiftOptions | null,
	textSelectable: boolean,
	closeToTray: boolean,
	closeToTrayChoiceMade: boolean,
	trayWidget: TrayWidgetSettings_Serialize,
};

export type CpuInfo = {
	name: string,
	vendor: string,
	coreCount: number,
	clock: number,
	clockUnit: string,
	cpuName: string,
};

export type DiskKind = "hdd" | "ssd" | "other";

export type DownloadEvent = { event: "started"; data: {
	contentLength: string | null,
} } | { event: "progress"; data: {
	chunkLength: string,
} } | { event: "finished" };

export type GpuMemoryUsage = {
	inUseBytes: string | null,
	allocBytes: string | null,
};

export type GpuMonitorData = {
	gpuId: string,
	gpuName: string,
	gpuUsage: number | null,
	gpuTemperature: number | null,
	gpuSource: string,
	gpuDedicatedMemoryUsageKb: number | null,
	gpuCoolerLevel: number | null,
};

/**
 *  GPU usage percentage together with the data-source identifier
 *  (e.g. "NVAPI", "ADL", "WMI", "DRM (AMD)", "IOKit")
 */
export type GpuUsageResult = {
	usage: number,
	source: string,
};

export type GraphSize = "sm" | "md" | "lg" | "xl" | "2xl";

export type GraphicInfo = {
	id: string,
	name: string,
	vendorName: string,
	clock: number,
	memorySize: string,
	memorySizeDedicated: string,
	coreCount: string | null,
};

/**
 *  Wire-format mirror of [`hardviz_core::settings::HardwareArchiveSettings`].
 * 
 *  The canonical definition lives in `hardviz_core::settings` so the
 *  archive worker (and any future Core consumer) doesn't need to know
 *  about Tauri or specta. This App-side struct exists only because the
 *  frontend wire format requires `specta::Type`.
 */
export type HardwareArchiveSettings = {
	enabled?: boolean,
	scheduledDataDeletion?: boolean,
	retentionDays?: number,
};

export type HardwareMonitorUpdate = {
	cpuUsage: number,
	memoryUsage: number,
	gpus: GpuMonitorData[],
	processorsUsage: number[],
};

export type HardwareType = "cpu" | "memory" | "gpu";

// Structure of settings to send to client
export type LineGraphColorStringSettings = {
	cpu: string,
	memory: string,
	gpu: string,
};

export type LineGraphType = "default" | "step" | "linear" | "basis";

export type MemoryInfo = {
	size: string,
	clock: number,
	clockUnit: string,
	memoryCount: number,
	totalSlots: number,
	memoryType: string,
	isDetailed: boolean,
};

export type MotherboardInfo = {
	manufacturer: string,
	product: string,
	version: string,
	serialNumber: string,
	biosVendor: string,
	biosVersion: string,
	biosReleaseDate: string,
};

export type NameValue = {
	name: string,
	value: number,
};

export type NetworkInfo = {
	description: string | null,
	macAddress: string | null,
	ipv4: string[],
	ipv6: string[],
	linkLocalIpv6: string[],
	ipSubnet: string[],
	defaultIpv4Gateway: string[],
	defaultIpv6Gateway: string[],
};

export type ProcessInfo = ProcessInfo_Serialize | ProcessInfo_Deserialize;

export type ProcessInfo_Deserialize = {
	// Process ID
	pid: number,
	// Process name
	name: string,
	// CPU usage
	cpuUsage: string,
	// Memory usage
	memoryUsage: string,
};

export type ProcessInfo_Serialize = {
	// Process ID
	pid: number,
	// Process name
	name: string,
	// CPU usage
	cpuUsage: string,
	// Memory usage
	memoryUsage: string,
};

export type SizeUnit = "B" | "KB" | "MB" | "GB";

export type StorageHealthStatus = "good" | "warning" | "critical" | "unknown";

export type StorageInfo = {
	name: string,
	size: number,
	sizeUnit: SizeUnit,
	free: number,
	freeUnit: SizeUnit,
	storageType: DiskKind,
	fileSystem: string,
};

export type StorageSmartDashboardSnapshot = {
	deviceId: string,
	displayName: string,
	model: string | null,
	protocol: string | null,
	capacityBytes: number | null,
	date: string,
	healthStatus: StorageHealthStatus,
	warningLevel: StorageWarningLevel,
	temperatureCelsius: number | null,
	powerOnHours: number | null,
	percentageUsed: number | null,
	availableSparePercent: number | null,
	reallocatedSectorCount: number | null,
	currentPendingSectorCount: number | null,
	offlineUncorrectableCount: number | null,
	mediaErrors: number | null,
	errorLogEntries: number | null,
	unsafeShutdownCount: number | null,
	warningReasons: string[],
	collectedAt: string,
};

/**
 *  Wire-format mirror of [`hardviz_core::settings::StorageSmartSettings`]. The
 *  canonical definition lives in `hardviz_core::settings` so the
 *  SMART snapshot worker doesn't need to know about Tauri or specta.
 */
export type StorageSmartSettings = {
	enabled?: boolean,
	retentionDays?: number,
};

export type StorageWarningLevel = "none" | "warning" | "critical" | "unknown";

export type SysInfo = {
	cpu: CpuInfo | null,
	memory: MemoryInfo | null,
	gpus: GraphicInfo[] | null,
	storage: StorageInfo[],
	motherboard: MotherboardInfo | null,
};

export type TemperatureUnit = "C" | "F";

export type Theme = "system" | "light" | "dark" | "darkPlus" | "sky" | "grove" | "sunset" | "nebula" | "orbit" | "cappuccino" | "espresso";

export type TrayMetric = "cpu" | "gpu" | "gpu-temp";

export type TrayWidgetSettings = TrayWidgetSettings_Serialize | TrayWidgetSettings_Deserialize;

export type TrayWidgetSettings_Deserialize = {
	enabled?: boolean,
	metricOrder?: TrayMetric[],
	visibleMetrics?: TrayMetric[],
	updateIntervalSecs?: number,
	metrics?: TrayMetric[],
};

export type TrayWidgetSettings_Serialize = {
	enabled: boolean,
	metricOrder: TrayMetric[],
	visibleMetrics: TrayMetric[],
	updateIntervalSecs: number,
};

export type UpdateMetadata = {
	version: string,
	currentVersion: string,
	notes: string | null,
	pubDate: string | null,
};

export type UpdaterError = "NoPendingUpdate" | { Updater: string };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    void _assertTypedErrorFollowsContract;
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        return { status: "error", error: e as E };
    }
}
// @ts-expect-error tauri-specta's generated contract assertion leaves E unused under noUnusedLocals.


const _assertTypedErrorFollowsContract: <T, E>(result: Promise<T>) => Promise<any> = typedError;

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

