name: 'Setup Linux Dependencies'
description: 'Install Linux build dependencies for Tauri'
inputs:
  extra-packages:
    description: 'Additional packages to install'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install Linux build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-dev \
          libwebkit2gtk-4.1-dev \
          librsvg2-dev \
          libjavascriptcoregtk-4.1-dev \
          libsoup-3.0-dev \
          ${{ inputs.extra-packages }}
      shell: bash

