[alias]
tauri-test = "test --workspace -- --test-threads=1 --nocapture"
tauri-test-cov = "llvm-cov --workspace -- --test-threads=1 --nocapture"
tauri-lint = "clippy --workspace -- -D warnings"
tauri-fmt = "fmt --all"
perf-test = "run --release --manifest-path perf-monitor/Cargo.toml"
