name: Check Version

on:
  pull_request:
    branches:
      - release/**
      - master

jobs:
  check-version:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: shm11C3/tauri-check-release-version@v1.0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: shm11C3
          repo: HardwareVisualizer
          tauri_config_path: ./src-tauri/tauri.conf.json
          tag_name_format: v{VERSION}
