name: Check Version

on:
  workflow_call:
    outputs:
      version:
        description: "Extracted App version"
        value: ${{ jobs.check-version.outputs.version }}

jobs:
  check-version:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.check-version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Version
        id: check-version
        uses: shm11C3/tauri-check-release-version@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: shm11C3
          repo: HardwareVisualizer
          tauri_config_path: ./src-tauri/tauri.conf.json
          tag_name_format: v{VERSION}
