name: "CI"

on:
  pull_request:
    branches:
      - master
      - develop
      - release/**
  push:
    branches:
      - develop
      - release/**

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: ./.github/workflows/ci-setup.yml
        with:
          platform: ${{ matrix.platform }}

      - name: Testing Tauri Backend
        run: cargo test --manifest-path src-tauri/Cargo.toml -- --test-threads=1 --nocapture

  lint:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: ./.github/workflows/ci-setup.yml
        with:
          platform: ${{ matrix.platform }}

      - name: check front end Lint
        run: npm run lint:ci

      - name: check Rust Lint
        run: cargo fmt --manifest-path src-tauri/Cargo.toml -- --check

      #- name: check Rust Clippy
      #  run: cargo clippy --manifest-path src-tauri/Cargo.toml -- -D warnings

  test-build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: ./.github/workflows/ci-setup.yml
        with:
          platform: ${{ matrix.platform }}

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ matrix.args }}
