name: "ci"

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - develop

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install frontend dependencies
        run: npm ci

      - name: check front end Lint
        run: npm run lint:ci

      - name: check Rust Lint
        run: cargo fmt --manifest-path src-tauri/Cargo.toml -- --check

      #- name: check Rust Clippy
      #  run: cargo clippy --manifest-path src-tauri/Cargo.toml -- -D warnings

      - name: Test Rust
        run: cargo test --manifest-path src-tauri/Cargo.toml

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ matrix.args }}
